config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :cryptoassets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "projects#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cryptoasset.rb
class Cryptoasset < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :project_links
end

app/models/project_link.rb
class ProjectLink < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cryptoassets_controller.rb
class CryptoassetsController < ApplicationController
  before_action :set_cryptoasset, only: %i[ show edit update destroy ]

  # GET /cryptoassets or /cryptoassets.json
  def index
    @cryptoassets = Cryptoasset.all
  end

  # GET /cryptoassets/1 or /cryptoassets/1.json
  def show
  end

  # GET /cryptoassets/new
  def new
    @cryptoasset = Cryptoasset.new
  end

  # GET /cryptoassets/1/edit
  def edit
  end

  # POST /cryptoassets or /cryptoassets.json
  def create
    @cryptoasset = Cryptoasset.new(cryptoasset_params)

    respond_to do |format|
      if @cryptoasset.save
        format.html { redirect_to cryptoasset_url(@cryptoasset), notice: "Cryptoasset was successfully created." }
        format.json { render :show, status: :created, location: @cryptoasset }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cryptoasset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptoassets/1 or /cryptoassets/1.json
  def update
    respond_to do |format|
      if @cryptoasset.update(cryptoasset_params)
        format.html { redirect_to cryptoasset_url(@cryptoasset), notice: "Cryptoasset was successfully updated." }
        format.json { render :show, status: :ok, location: @cryptoasset }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cryptoasset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptoassets/1 or /cryptoassets/1.json
  def destroy
    @cryptoasset.destroy

    respond_to do |format|
      format.html { redirect_to cryptoassets_url, notice: "Cryptoasset was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cryptoasset
      @cryptoasset = Cryptoasset.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cryptoasset_params
      params.require(:cryptoasset).permit(:name, :description, :ticker)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        render json: {}
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptoassets_helper.rb
module CryptoassetsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/cryptoassets/_cryptoasset.html.erb
<div id="<%= dom_id cryptoasset %>">
  <p>
    <strong>Name:</strong>
    <%= cryptoasset.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= cryptoasset.description %>
  </p>

  <p>
    <strong>Ticker:</strong>
    <%= cryptoasset.ticker %>
  </p>

</div>

app/views/cryptoassets/_form.html.erb
<%= form_with(model: cryptoasset) do |form| %>
  <% if cryptoasset.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cryptoasset.errors.count, "error") %> prohibited this cryptoasset from being saved:</h2>

      <ul>
        <% cryptoasset.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :ticker, style: "display: block" %>
    <%= form.text_field :ticker %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cryptoassets/edit.html.erb
<h1>Editing cryptoasset</h1>

<%= render "form", cryptoasset: @cryptoasset %>

<br>

<div>
  <%= link_to "Show this cryptoasset", @cryptoasset %> |
  <%= link_to "Back to cryptoassets", cryptoassets_path %>
</div>

app/views/cryptoassets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cryptoassets</h1>

<div id="cryptoassets">
  <% @cryptoassets.each do |cryptoasset| %>
    <%= render cryptoasset %>
    <p>
      <%= link_to "Show this cryptoasset", cryptoasset %>
    </p>
  <% end %>
</div>

<%= link_to "New cryptoasset", new_cryptoasset_path %>

app/views/cryptoassets/new.html.erb
<h1>New cryptoasset</h1>

<%= render "form", cryptoasset: @cryptoasset %>

<br>

<div>
  <%= link_to "Back to cryptoassets", cryptoassets_path %>
</div>

app/views/cryptoassets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cryptoasset %>

<div>
  <%= link_to "Edit this cryptoasset", edit_cryptoasset_path(@cryptoasset) %> |
  <%= link_to "Back to cryptoassets", cryptoassets_path %>

  <%= button_to "Destroy this cryptoasset", @cryptoasset, method: :delete %>
</div>

app/views/home/index.html.erb
<h2> hello </h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>🧙‍♀️🧙‍♂️</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">

  </head>

  <body>
    <div id="navbar" style="height=250px; background-color: black; padding: 0px;">
      <h1 style="font-family: 'Playfair Display', serif; color: white; font-size: <%= Math::PI/2 %>em; padding-left: 0.5em;">Sorcery</h1>
    </div>

    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= project.url %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>